name: Build C++ Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild Il2CppRuntimeDumper.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: x64/Release/*.dll
